Roguelike 1
fancy-memers/ifmo-2020-software-design pull request #16
Opened 2020-05-06 11:28 UTC by dima74

Участники команды:

* Иван Пости
* Николай Свиридов
* Артём Бобров
* Дмитрий Мурзин

2020-05-18 18:03 UTC, ottergottaott requested changes
Отличная работа.

Мб, в будущих версиях стоит разрешить выходить за границу экрана там, где нет явной стены. Можно, например, "циклично" перемещать игрока на другую сторону. Сейчас ощущается как недоработанное ограничение :)  

Юнит-тестов и комментариев нет совсем, их придется написать

2020-05-18 18:03 UTC, aleksZubakov commented on src/main/kotlin/org/fancy/memers/model/Block.kt
> +        get() = TileColor.fromString("#3E3D32")
Я не уверен, что мы хотим при каждом вызове `get` каждого `Block` выделять память, создавая `TileColor`.  Мб, мы все-таки понимаем, что таких вызовов может быть много (терпимо, но много) и хотим вычислить свойства заранее. 

Сейчас сетка небольшая и некритично, но о таких вещах стоит задумываться.

Тут же, кстати, можно было дойти до использования паттерна легковес (странный перевод английского flyweight): давайте вместо создания полноценных тайлов
-  создадим три неизменяемых объекта, описывающих три вида тайлов (как раз `Wall`, `Floor`, `Empty`), очевидно, сделаем для этого отдельную иерархию
- все также будем педставлять тайлы на карте в виде `Block`
- но теперь `Block` будет содержать один из трех видов тайлов (при создании будем передавать необходимый) и позицию

В будущем новые виды тайлов можно будет также легко добавить, как и сейчас, но памяти будем тратить меньше.

2020-05-18 18:09 UTC, aleksZubakov commented on src/main/kotlin/org/fancy/memers/ui/main/board/GameArea.kt
> +                else -> Tile.newBuilder()
И тут тоже можно было `Tile` не создавать заново, похоже, а передавать ссылку

2020-06-22 14:22 UTC, dima74 commented
@aleksZubakov спасибо за комментарии. Добавили тесты на World, BoardGenerator и сериализацию. Также добавили комментарии

2020-06-22 14:24 UTC, dima74 commented on src/main/kotlin/org/fancy/memers/model/Block.kt
> +        get() = TileColor.fromString("#3E3D32")
Хорошее замечание. В качестве простого решения вынесли объекты `TileColor` в константы

2020-08-23 17:58 UTC, closed without merging