Implement confusion spell
fancy-memers/ifmo-2020-software-design pull request #21
Opened 2020-05-28 20:31 UTC by FirstTimeInForever

2020-05-28 20:31 UTC, FirstTimeInForever commented
Не забыть обновить диздок.

2020-05-29 14:29 UTC, aibobrov approved these changes

2020-05-29 14:29 UTC, artbobrov commented on src/main/kotlin/org/fancy/memers/ui/main/board/GameModification.kt
>      // TODO: сюда пойдут спеллы отдельным классов, типо SpellAttack ...
коммент б убрать

2020-05-30 08:29 UTC, dima74 reviewed
Если я нажимаю "вверх", то player может остаться на месте или переместиться вверх на две клетки. А в задании просят так: 
> например, при попытке сделать шаг вверх игрок с равной вероятностью делает шаг вверх, вверх-влево или вверх-вправо

Please also resolve conflicts

2020-05-31 14:10 UTC, FirstTimeInForever commented
@dima74 Так было задумано.

2020-05-31 16:14 UTC, aibobrov requested changes

2020-05-31 16:14 UTC, artbobrov commented on src/main/kotlin/org/fancy/memers/model/ai/AggressiveEnemyBehaviour.kt
> +//        val movement = GameModification.Identity
шо за коммент?

2020-05-31 16:14 UTC, artbobrov commented on src/main/kotlin/org/fancy/memers/model/ai/BaseEnemyBehaviour.kt
> +        val shifts = listOf(1 to 1, -1 to -1, 1 to -1, -1 to 1)
цэ высер

2020-05-31 16:14 UTC, artbobrov commented on src/main/kotlin/org/fancy/memers/model/ai/BaseEnemyBehaviour.kt
> +            return listOf(direction.copy(x = 0), direction.copy(y = 0)).random().endPoint
отвратительная строчка

2020-05-31 16:14 UTC, artbobrov commented on src/main/kotlin/org/fancy/memers/ui/main/MainGameView.kt
> +            in KeyboardControls.SKIP_TURN -> GameModification.Identity
зачем это? почему не `{}`?

2020-05-31 16:14 UTC, artbobrov commented on src/main/kotlin/org/fancy/memers/ui/main/MainGameView.kt
> +        gameArea.apply(GameModification.Step)
??

2020-05-31 16:14 UTC, FirstTimeInForever commented on src/main/kotlin/org/fancy/memers/model/ai/BaseEnemyBehaviour.kt
> +        val shifts = listOf(1 to 1, -1 to -1, 1 to -1, -1 to 1)
Це твоя работа была

2020-05-31 16:15 UTC, FirstTimeInForever commented on src/main/kotlin/org/fancy/memers/model/ai/BaseEnemyBehaviour.kt
> +            return listOf(direction.copy(x = 0), direction.copy(y = 0)).random().endPoint
Всё ещё твоя работа

2020-05-31 16:15 UTC, FirstTimeInForever commented on src/main/kotlin/org/fancy/memers/ui/main/MainGameView.kt
> +            in KeyboardControls.SKIP_TURN -> GameModification.Identity
Потому что есть `Identity`

2020-05-31 16:15 UTC, FirstTimeInForever commented on src/main/kotlin/org/fancy/memers/ui/main/MainGameView.kt
> +        gameArea.apply(GameModification.Step)
???

2020-05-31 16:15 UTC, artbobrov commented on src/main/kotlin/org/fancy/memers/model/ai/BaseEnemyBehaviour.kt
> +        val shifts = listOf(1 to 1, -1 to -1, 1 to -1, -1 to 1)
я говорил про проекцию вектора на рандомную ось, а не костыль

2020-05-31 16:29 UTC, merged