escape menu without save
fancy-memers/ifmo-2020-software-design pull request #22
Opened 2020-05-29 14:35 UTC by NikolaiSviridov

2020-05-29 19:46 UTC, FirstTimeInForever requested changes

2020-05-29 19:46 UTC, FirstTimeInForever commented on src/main/kotlin/org/fancy/memers/ui/main/escape/EscapeScreenConfig.kt
> +}
`\n`

2020-05-29 19:46 UTC, FirstTimeInForever commented on src/main/kotlin/org/fancy/memers/ui/main/KeyboardControls.kt
> +    val ESC = listOf(KeyCode.ESCAPE)
`ESCAPE_MENU`

2020-05-29 19:46 UTC, FirstTimeInForever commented on src/main/kotlin/org/fancy/memers/ui/main/escape/EscapeMenuView.kt
> +                saveToFile(
Отвратительное форматирование. Вина идеи.

2020-05-30 20:17 UTC, aibobrov approved these changes

2020-05-31 09:55 UTC, dima74 requested changes
* Please resolve merge conflicts
* Ещё у меня теперь нет монстров при "Start random", может быть это само исправится если пофиксить merge conflicts
* Если попытаться "Save to file", но не ввести путь к файлу, то возникает FileNotFoundException. Думаю надо показывать какое-нибудь сообщение об ошибке в этом случае (для меня например было вообще не очевидно что надо вводить путь к файлу, я думал что если путь к файлу не введён, то будет автоматически выбран какой-нибудь путь)

2020-05-31 15:06 UTC, NikolaiSviridov commented
> * Please resolve merge conflicts
Поправил.
> * Ещё у меня теперь нет монстров при "Start random", может быть это само исправится если пофиксить merge conflicts
После merge conflicts работает.

2020-05-31 15:06 UTC, NikolaiSviridov commented
> > * Please resolve merge conflicts
  Поправил.
> > * Ещё у меня теперь нет монстров при "Start random", может быть это само исправится если пофиксить merge conflicts
> >   После merge conflicts работает.

2020-05-31 16:27 UTC, merged