Logging
fancy-memers/ifmo-2020-software-design pull request #23
Opened 2020-05-30 20:16 UTC by artbobrov

2020-05-30 20:23 UTC, FirstTimeInForever requested changes
В логе помещается всего 4 записи. Может стоит не записывать перемещения? Иначе, если на карте будет больше 3 врагов, то какие-то события будут просто не отображаться.

2020-05-30 20:23 UTC, FirstTimeInForever commented on build.gradle.kts
> +    api("io.github.serpro69:kotlin-faker:1.1.+")
Вот это клёво.

2020-05-30 20:25 UTC, artbobrov commented
@FirstTimeInForever ну да, можно

2020-05-30 20:53 UTC, FirstTimeInForever approved these changes

2020-05-31 09:59 UTC, dima74 approved these changes

2020-05-31 10:00 UTC, merged