Roguelike 3
fancy-memers/ifmo-2020-software-design pull request #27
Opened 2020-05-31 19:36 UTC by dima74

2020-06-23 14:39 UTC, ottergottaott requested changes
- Странно, что не сохраняет игру, если файла по заданному пути не существует. Наверное, стоит попытаться его создать.
- Почему-то уже в процессе игры начать новую можно только из файла, но не случайную
- При выкидывании двух предметов обратно поднимается только один 

В целом, весьма хорошо. Засчитываю roguelike 1, 2

2020-06-23 14:39 UTC, ottergottaott commented on src/main/kotlin/org/fancy/memers/ui/main/board/GameArea.kt
>      }
:c

2020-06-23 14:39 UTC, aleksZubakov commented on src/main/kotlin/org/fancy/memers/ui/main/board/World.kt
> +                targetCreature.effects.add(ConfusionEffect())
Напомню, что в задании требовалось

> Используя паттерн "Декоратор", реализовать заклинание конфузии, накладываемое на игрока. 

Здесь совсем не декоратор: его идея в том, что мы оборачиваем существующий объект динамически, получая возможность добавить новую функциональность. 

У вас же просто добавляются эффекты в существующую сущность. Вполне адекватный рабочий вариант, но в задании требуется не это.

2020-06-23 14:39 UTC, aleksZubakov commented on src/main/kotlin/org/fancy/memers/ui/main/MainGameView.kt
> +                    GameModification.Move(gameArea.world.player, position)
Это вкусовщина, но мне кажется, что тут полноценная функция была бы чуть более наглядной, чем лямбда.

2020-06-23 14:39 UTC, aleksZubakov commented on src/main/kotlin/org/fancy/memers/model/generator/CellularAutomataBoardGenerator.kt
> +        var gameBoard = initialGenerator.generateMap(false, false).toMutableMap()
Тут IDEA подсказывает, что лучше при передаче литералов в кач-ве аргументов именовать аргументы

2020-06-23 14:43 UTC, aleksZubakov commented
Так, а что с диздоком?

2020-06-23 14:55 UTC, NikolaiSviridov commented
> Так, а что с диздоком?

Попытаемся поправить в ближайшее время

2020-06-30 00:36 UTC, aleksZubakov commented
Засчитываю

2020-08-23 17:58 UTC, closed without merging